version: '3.4'

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data 
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes:
        - rabbitmq_volume:/var/lib/rabbitmq
volumes:
  redis_volume:
  rabbitmq_volume:
